// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.924
package main

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"context"
	"log/slog"
	"net/http"
	"time"

	"github.com/zodimo/go-live-templ-clock-example/pkg/templrenderer"

	"github.com/jfyne/live"
)

const (
	tick = "tick"
)

type clock struct {
	Time time.Time
}

func newClock(s *live.Socket) *clock {
	c, ok := s.Assigns().(*clock)
	if !ok {
		return &clock{
			Time: time.Now(),
		}
	}
	return c
}

func (c clock) FormattedTime() string {
	return c.Time.Format("15:04:05")
}

func mount(ctx context.Context, s *live.Socket) (any, error) {
	// Take the socket data and tranform it into our view model if it is
	// available.
	c := newClock(s)

	// If we are mouting the websocket connection, trigger the first tick
	// event.
	if s.Connected() {
		go func() {
			time.Sleep(1 * time.Second)
			s.Self(ctx, tick, time.Now())
		}()
	}
	return c, nil
}

func PageView(state PageState) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><head><title>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.JoinStringErrs(state.Clock.FormattedTime())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `clock/main.templ`, Line: 56, Col: 44}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var2))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</title><meta name=\"color-scheme\" content=\"light dark\"><link rel=\"stylesheet\" href=\"https://cdn.jsdelivr.net/npm/@picocss/pico@2/css/pico.classless.min.css\"><style>\n            body {\n                border-top: 5px solid red;\n                margin: 0;\n                padding: 1rem;\n            }\n            body.live-connected {\n                border-top: none;\n            }\n        </style></head><body>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = ClockView(state.Clock).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "<!-- This is embedded in the binary and enables live to work --><script type=\"text/javascript\" src=\"/live.js\"></script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

type PageState struct {
	Clock *clock
}

func LiveTempl(rc *live.RenderContext) templ.Component {
	state := PageState{
		Clock: newClock(rc.Socket),
	}
	return PageView(state)
}

func main() {
	h := live.NewHandler(templrenderer.WithTemplRenderer(LiveTempl))

	// Set the mount function for this handler.
	h.MountHandler = mount

	// Server side events.

	// tick event updates the clock every second.
	h.HandleSelf(tick, func(ctx context.Context, s *live.Socket, d any) (any, error) {
		// Get our model
		c := newClock(s)
		// Update the time.
		c.Time = d.(time.Time)
		// Send ourselves another tick in a second.
		go func(sock *live.Socket) {
			time.Sleep(1 * time.Second)
			sock.Self(ctx, tick, time.Now())
		}(s)
		return c, nil
	})

	// Run the server.
	http.Handle("/", live.NewHttpHandler(context.Background(), h))
	http.Handle("/live.js", live.Javascript{})
	http.Handle("/auto.js.map", live.JavascriptMap{})
	slog.Info("server", "link", "http://localhost:8080")
	http.ListenAndServe(":8080", nil)
}

var _ = templruntime.GeneratedTemplate
